services:
  dock-discovry-service:
    build: ./discovry-service
    container_name: dock-discovry-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:8761/actuator/health" ]
      interval:  10s
      retries:  4
  dock-config-service:
    build: ./config-service
    container_name: dock-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://dock-discovry-service:8761/eureka
    depends_on:
      dock-discovry-service:
        condition:  service_healthy
  dock-etudiant-service:
    build: ./etudiant-service
    container_name: dock-etudiant-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:8081/actuator/health" ]
    environment:
      - DISCOVERY_SERVICE_URL=http://dock-discovry-service:8761/eureka
      - CONFIG_SERVICE_URL=http://dock-config-service:9999
    depends_on:
      dock-config-service:
        condition: service_healthy
  dock-unite-service:
    build: ./unite-service
    container_name: dock-unite-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://dock-discovry-service:8761/eureka
      - CONFIG_SERVICE_URL=http://dock-config-service:9999
    depends_on:
      dock-etudiant-service:
        condition: service_healthy
  dock-gateway-service:
    build: ./gateway-service
    container_name: dock-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://dock-discovry-service:8761/eureka
      - CONFIG_SERVICE_URL=http://dock-config-service:9999
    depends_on:
      dock-unite-service:
        condition:
          service_healthy